export const quiz = {
  appLocale: {
    landingHeaderText: "<questionLength> Questões",
    question: "Questão ",
    startQuizBtn: "Iniciar Quiz",
    resultFilterAll: "Todas",
    resultFilterCorrect: "Correto",
    resultFilterIncorrect: "Incorreto",
    resultFilterUnanswered: "Não respondido",
    prevQuestionBtn: "Anterior",
    nextQuestionBtn: "Proximo",
    resultPagePoint: "Você fez <correctPoints> de <totalPoints> pontos",
    singleSelectionTagText: "Selecione uma opção",
    multipleSelectionTagText: "Selecione uma ou mais opções",
    pickNumberOfSelection: "Selecione <numberOfSelection>",
    marksOfQuestion: "(<marks> pontos)",
    resultPageHeaderText:
      "Você acertou <correctIndexLength> de <questionLength> perguntas",
  },
  quizTitle: "Quiz de Matemática Financeira",
  quizSynopsis:
    "Teste seus conhecimentos em matemática financeira, incluindo juros simples, compostos, porcentagem e mais!",
  progressBarColor: "#9de1f6",
  nrOfQuestions: "16",
  questions: [
    {
      question: "O que representa o capital em uma aplicação financeira?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "O montante final após a aplicação dos juros.",
        "O valor dos juros pagos ao final do prazo.",
        "A quantia inicial investida ou financiada.",
        "O tempo necessário para a aplicação gerar juros.",
        "A taxa de juros aplicada ao investimento.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "Qual das opções abaixo corresponde corretamente à definição de juros?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "O valor inicial de um investimento.",
        "A soma do capital com os rendimentos.",
        "A quantia aplicada no início da operação.",
        "A remuneração pelo uso do capital durante um período.",
        "O tempo necessário para dobrar um investimento.",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "Porcentagem é uma forma de representar uma fração com denominador igual a:",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["10", "50", "100", "1000", "1"],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "5",
    },
    {
      question: "Os juros simples são calculados com base:",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "No montante final acumulado",
        "No capital inicial, sem reincidência de juros sobre juros",
        "Na taxa de inflação do período",
        "No tempo decorrido sem considerar a taxa de juros",
        "No valor presente e futuro da aplicação",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "Qual das expressões abaixo representa a forma correta de cálculo de juros no regime de capitalização simples?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "j = C.i.t",
        "j = C.(1+t)^t",
        "j = C+i+t",
        "j = (C+j).i",
        "j = (C.i)^t",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question: "Os juros compostos diferem dos juros simples porque:",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "A taxa de juros não influencia no cálculo",
        "Os juros são calculados apenas uma vez no período total",
        "O valor dos juros acumulados é somado ao capital para o cálculo dos juros futuros",
        "O montante final é sempre menor do que nos juros simples",
        "O tempo não influencia o crescimento do montante",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "No regime de capitalização composta, a taxa de juros incide sobre:",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "O capital inicial durante todo o período.",
        "O valor dos juros acumulados apenas no primeiro período.",
        "O valor do montante do período anterior.",
        "Apenas o capital inicial e não sofre alterações ao longo do tempo.",
        "O saldo final do investimento sem considerar os períodos intermediários.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "Qual das expressões abaixo representa a forma de cálculo do montante no regime de capitalização composta?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "M = C.(1+i.t)",
        "M = C + (C.i.t)",
        "M = C.(1+i)^t",
        "M = C.(1+i.t)",
        "M = C.i^t",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question: "Ao passar por uma loja João se deparou com o cartaz abaixo:",
      questionType: "text",
      questionPic: "/q9.png",
      answerSelectionType: "single",
      answers: [
        "R$ 180,00",
        "R$ 170,00",
        "R$ 160,00",
        "R$ 150,00",
        "R$ 190,00",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "5",
    },
    {
      question:
        "Se um produto custa R$ 2.000,00 e é parcelado em 5 vezes iguais sem juros, qual o valor de cada parcela?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "R$ 350,00",
        "R$ 400,00",
        "R$ 450,00",
        "R$ 500,00",
        "R$ 550,00",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "5",
    },
    {
      question:
        "Se um produto teve um aumento de 15% no seu preço original de R$ 200,00, qual será o novo preço?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "R$ 210,00",
        "R$ 220,00",
        "R$ 230,00",
        "R$ 240,00",
        "R$ 250,00",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "5",
    },
    {
      question:
        "Em uma análise crítica de um problema financeiro envolvendo juros compostos, qual aspecto deve ser considerado?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Apenas a taxa de juros aplicada",
        "O tempo de aplicação e a taxa de juros",
        "Somente o montante final da aplicação",
        "O capital inicial e o método de cálculo usado",
        "Nenhuma alternativa anterior",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "João aplicou R$20.000,00 durante 3 meses com juros simples de 6% ao mês. Qual o valor recebido ao final?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "R$ 21.600,00",
        "R$ 24.800,00",
        "R$ 22.400,00",
        "R$ 23.600,00",
        "R$ 25.200,00",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "Em uma loja, um aparelho de TV é vendido com as seguintes condições:",
      questionType: "text",
      questionPic: "/q14.jpg",
      answerSelectionType: "single",
      answers: ["9,55%", "15,15%", "18,75%", "20,25%", "22,01%"],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "10",
    },
    {
      question:
        "Maria quer comprar uma TV de R$ 1.500,00 em 3x de R$ 500,00, e aplicou o restante com rendimento de 1% ao mês. Quanto ela tinha reservado inicialmente?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "R$ 1.450,20",
        "R$ 1.480,20",
        "R$ 1.485,20",
        "R$ 1.495,20",
        "R$ 1.490,20",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "15",
    },
    {
      question:
        "Dois bancos oferecem: A) Juros simples 6% a.m., B) Juros compostos 4% a.m., por 10 meses. Qual rende mais?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Banco A, pois o montante será de R$ 24.000,00.",
        "Banco B, pois o montante será de R$ 22.116,96.",
        "Banco A, pois o montante será de R$ 20.400,00.",
        "Banco B, pois o montante será de R$ 21.502,40.",
        "Ambos geram o mesmo montante.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Correto!",
      messageForIncorrectAnswer: "Resposta incorreta.",
      point: "15",
    },
  ],
};
